<?php

namespace App\Data\Themes;

use App\Data\Base;

class Theme extends Base
{
    protected $type = 'themes';

    protected $nameField;
    protected $imgField;

    protected function getAttributesData() : array
    {
        return [
            'name' => $this->faker->sentence(4),
            'img' => $this->faker->uuid
        ];
    }

    protected function getRelationshipsData() : array
    {
        return parent::getRelationshipsData(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getNameField()
    {
        return $this->nameField ?? $this->faker->sentence(4, true);
    }

    /**
     * @param mixed $nameField
     * @return self
     */
    public function setNameField($nameField): self
    {
        $this->nameField = $nameField;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImgField()
    {
        return $this->imgField ?? $this->faker->uuid;
    }

    /**
     * @param mixed $imgField
     * @return self
     */
    public function setImgField($imgField): self
    {
        $this->imgField = $imgField;

        return $this;
    }
}