<?php

namespace App\Data\PagesTypes;

use App\Data\Base;

class PageType extends Base
{
    protected $type = 'pages-types';

    protected $slugField;
    protected $nameEnField;
    protected $nameDeField;
    protected $isMenuField;

    protected function getAttributesData() : array
    {
        return [
            'slug' => $this->getSlugField(),
            'name-en' => $this->getNameEnField(),
            'name-de' => $this->getNameDeField(),
            'is-menu' => $this->getIsMenuField()
        ];
    }

    protected function getRelationshipsData() : array
    {
        return parent::getRelationshipsData(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getSlugField()
    {
        return $this->slugField ?? $this->faker->slug();
    }

    /**
     * @param mixed $slugField
     * @return self
     */
    public function setSlugField($slugField): self
    {
        $this->slugField = $slugField;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getNameEnField()
    {
        return $this->nameEnField ?? $this->faker->sentence(4);
    }

    /**
     * @param mixed $nameEnField
     * @return self
     */
    public function setNameEnField($nameEnField): self
    {
        $this->nameEnField = $nameEnField;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getNameDeField()
    {
        return $this->nameDeField ?? $this->faker->sentence(4);
    }

    /**
     * @param mixed $nameDeField
     * @return self
     */
    public function setNameDeField($nameDeField): self
    {
        $this->nameDeField = $nameDeField;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getIsMenuField()
    {
        return (int) ($this->isMenuField ?? $this->faker->boolean());
    }

    /**
     * @param mixed $isMenuField
     * @return self
     */
    public function setIsMenuField($isMenuField): self
    {
        $this->isMenuField = $isMenuField;

        return $this;
    }


}