<?php

namespace App\Data\PagesTypes;

use App\Data\Base;

class PageType extends Base
{
    protected $type = 'pages-types';

    protected function getAttributesData() : array
    {
        return [
            'slug' => $this->faker->slug(),
            'name-en' => $this->faker->sentence(4),
            'name-de' => $this->faker->sentence(3),
            'is-menu' => (int) $this->faker->boolean()
        ];
    }

    protected function getRelationshipsData() : array
    {
        return parent::getRelationshipsData(); // TODO: Change the autogenerated stub
    }
}